// src/App.tsx
import { createEffect, createSignal } from "solid-js";
import styles from "./App.module.css";
import { AuthSession, SupabaseClient } from "@supabase/supabase-js";
import { Database } from "./database.types";
import { Auth } from "./Auth";
import { Account } from "./Account";

export const App = ({ supabase }: { supabase: SupabaseClient<Database> }) => {
	const [session, setSession] = createSignal<AuthSession | null>(null);
	const [initializing, setInitializing] = createSignal(true);

	createEffect(() => {
		supabase.auth.getSession().then(({ data: { session } }) => {
			setInitializing(false);
			setSession(session);
		});

		supabase.auth.onAuthStateChange((_event, session) => {
			setInitializing(false);
			setSession(session);
		});
	});

	return (
		<div class={styles.App}>
			<header class={styles.header}>
				<div class="container" style={{ padding: "50px 0 100px 0" }}>
					{initializing() ? null : !session() ? (
						<Auth supabase={supabase} />
					) : (
						<Account supabase={supabase} session={session()!} />
					)}
				</div>
			</header>
		</div>
	);
};

// src/App.svelte
<script lang="ts">
	import type { AuthSession } from '@supabase/supabase-js';
	import Auth from './Auth.svelte';
	import Account from './Account.svelte';
	import type { AppSupabase } from './app-supabase';

	type AppProps = {
		appSupabase: AppSupabase
	}

	const { appSupabase }: AppProps = $props();

	let session: AuthSession | null = $state(null);

	$effect(() => {
		if (!appSupabase) {
			console.warn(`No appSupabase (${appSupabase})`);
			return;
		}

		appSupabase.auth.getSession().then(({ data }) => {
			session = data.session;
		});

		appSupabase.auth.onAuthStateChange((_event, receivedSession) => {
			session = receivedSession;
		});
	});
</script>

<div class="app">
	<header class="header">
		<div class="container" style:padding="50px 0 100px 0">
			{#if !session}
				<Auth {appSupabase} />
			{:else}
				<Account {appSupabase} {session} />
			{/if}
		</div>
	</header>
</div>

<style>
    .app {
        text-align: center;
    }

    .header {

        min-height: 100vh;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        font-size: calc(10px + 2vmin);
        color: white;
    }
</style>
